version: '3.8'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=files_send_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: